version: "3.9"

services:
  db:
    image: mysql:latest
    container_name: flowlysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: radosavp4320
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
