FROM node:20-alpine

WORKDIR /app

ARG NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ARG CLERK_SECRET_KEY
ARG DATABASE_URL
ARG NEXT_PUBLIC_URL_ENDPOINT
ARG NEXT_PUBLIC_IMAGEKIT_KEY
ARG IMAGEKIT_PRIVATE_KEY
ARG CLERK_WEBHOOK_SIGNING_SECRET

ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ENV CLERK_SECRET_KEY=$CLERK_SECRET_KEY
ENV DATABASE_URL=$DATABASE_URL
ENV NEXT_PUBLIC_URL_ENDPOINT=$NEXT_PUBLIC_URL_ENDPOINT
ENV NEXT_PUBLIC_IMAGEKIT_KEY=$NEXT_PUBLIC_IMAGEKIT_KEY
ENV IMAGEKIT_PRIVATE_KEY=$IMAGEKIT_PRIVATE_KEY
ENV CLERK_WEBHOOK_SIGNING_SECRET=$CLERK_WEBHOOK_SIGNING_SECRET

COPY . .

RUN yarn install --frozen-lockfile

RUN npx prisma generate

RUN yarn run build

EXPOSE 3000

CMD ["yarn", "start"]